name: Publish PDF-Merge-Service for Github-ContainerRegistry

on:
  push

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username chennenberg@gmx.de --password ${{ secrets.REGISTRY_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/hennenberg/pdf-merge-service:latest
          docker push ghcr.io/hennenberg/pause-sepa:latest
